name: "create-repo-from-repo-template"
description: "An action to create a repository from a repository template in an organization"
inputs:
  organization:
    description: "GitHub organization name"
    required: true
  repo_name:
    description: "GitHub repository name to create"
    required: true
  repo_template:
    description: "GitHub repository template to use"
    required: true
  pat:
    description: "Personal access token if using that to auth instead of an app"
    required: false
  api_url:
    description: "Source GitHub API URL"
    required: false
    default: "https://api.github.com"
  is_debug:
    description: "Debug mode"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
